//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dna.NetCore.Core.BLL.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dna.NetCore.Core.BLL.Resources.ValidationMessages", typeof(ValidationMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Abbreviation Is Required.
        /// </summary>
        public static string AbbreviationIsRequired {
            get {
                return ResourceManager.GetString("AbbreviationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Added By Is Required.
        /// </summary>
        public static string AddedByIsRequired {
            get {
                return ResourceManager.GetString("AddedByIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Added Date Is Required.
        /// </summary>
        public static string AddedDateIsRequired {
            get {
                return ResourceManager.GetString("AddedDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Address Type is Required.
        /// </summary>
        public static string AddressTypeIsRequired {
            get {
                return ResourceManager.GetString("AddressTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Area Code Is Required.
        /// </summary>
        public static string AreaCodeIsRequired {
            get {
                return ResourceManager.GetString("AreaCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to BEGINCopySectionToEveryModule.
        /// </summary>
        public static string BEGINCopySectionToEveryModule {
            get {
                return ResourceManager.GetString("BEGINCopySectionToEveryModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to BEGINModuleSpecificSection.
        /// </summary>
        public static string BEGINModuleSpecificSection {
            get {
                return ResourceManager.GetString("BEGINModuleSpecificSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Changed By Is Required.
        /// </summary>
        public static string ChangedByIsRequired {
            get {
                return ResourceManager.GetString("ChangedByIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Changed Date Is Required.
        /// </summary>
        public static string ChangedDateIsRequired {
            get {
                return ResourceManager.GetString("ChangedDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to City is Required.
        /// </summary>
        public static string CityIsRequired {
            get {
                return ResourceManager.GetString("CityIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Claim Issuer Is Required.
        /// </summary>
        public static string ClaimIssuerIsRequired {
            get {
                return ResourceManager.GetString("ClaimIssuerIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Claim Not Found.
        /// </summary>
        public static string ClaimNotFound {
            get {
                return ResourceManager.GetString("ClaimNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Claim Type Is Required.
        /// </summary>
        public static string ClaimTypeIsRequired {
            get {
                return ResourceManager.GetString("ClaimTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Claim Value Type Is Required.
        /// </summary>
        public static string ClaimValueTypeIsRequired {
            get {
                return ResourceManager.GetString("ClaimValueTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Code Is Required.
        /// </summary>
        public static string CodeIsRequired {
            get {
                return ResourceManager.GetString("CodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Content Type Is Required.
        /// </summary>
        public static string ContentTypeIsRequired {
            get {
                return ResourceManager.GetString("ContentTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Country Code Is Required.
        /// </summary>
        public static string CountryCodeIsRequired {
            get {
                return ResourceManager.GetString("CountryCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Country Is Required.
        /// </summary>
        public static string CountryIsRequired {
            get {
                return ResourceManager.GetString("CountryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to County Is Required.
        /// </summary>
        public static string CountyIsRequired {
            get {
                return ResourceManager.GetString("CountyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Data Exception occured.
        /// </summary>
        public static string DataException {
            get {
                return ResourceManager.GetString("DataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Data is Required.
        /// </summary>
        public static string DataIsRequired {
            get {
                return ResourceManager.GetString("DataIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Display Name Is Required.
        /// </summary>
        public static string DisplayNameIsRequired {
            get {
                return ResourceManager.GetString("DisplayNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate Abbreviation Found.
        /// </summary>
        public static string DuplicateAbbreviationFound {
            get {
                return ResourceManager.GetString("DuplicateAbbreviationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate Claim Name Found.
        /// </summary>
        public static string DuplicateClaimNameFound {
            get {
                return ResourceManager.GetString("DuplicateClaimNameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate ClaimType Found.
        /// </summary>
        public static string DuplicateClaimTypeFound {
            get {
                return ResourceManager.GetString("DuplicateClaimTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate Code Found.
        /// </summary>
        public static string DuplicateCodeFound {
            get {
                return ResourceManager.GetString("DuplicateCodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate Display Name Found.
        /// </summary>
        public static string DuplicateDisplayNameFound {
            get {
                return ResourceManager.GetString("DuplicateDisplayNameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate LCID Decimal Found.
        /// </summary>
        public static string DuplicateLCIDDecimalFound {
            get {
                return ResourceManager.GetString("DuplicateLCIDDecimalFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate Name Found.
        /// </summary>
        public static string DuplicateNameFound {
            get {
                return ResourceManager.GetString("DuplicateNameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate System Name Found.
        /// </summary>
        public static string DuplicateSystemNameFound {
            get {
                return ResourceManager.GetString("DuplicateSystemNameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate UserName: &apos;{0}&apos; found.
        /// </summary>
        public static string DuplicateUserNameFound {
            get {
                return ResourceManager.GetString("DuplicateUserNameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate Value Found.
        /// </summary>
        public static string DuplicateValueFound {
            get {
                return ResourceManager.GetString("DuplicateValueFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate Value Type Found.
        /// </summary>
        public static string DuplicateValueTypeFound {
            get {
                return ResourceManager.GetString("DuplicateValueTypeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email is Invalid.
        /// </summary>
        public static string EmailIsInvalid {
            get {
                return ResourceManager.GetString("EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ENDCopySectionToEveryModule.
        /// </summary>
        public static string ENDCopySectionToEveryModule {
            get {
                return ResourceManager.GetString("ENDCopySectionToEveryModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ENDModuleSpecificSection.
        /// </summary>
        public static string ENDModuleSpecificSection {
            get {
                return ResourceManager.GetString("ENDModuleSpecificSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Facebook User Name Is Required.
        /// </summary>
        public static string FacebookUserNameIsRequired {
            get {
                return ResourceManager.GetString("FacebookUserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to File Extension Is Required.
        /// </summary>
        public static string FileExtensionIsRequired {
            get {
                return ResourceManager.GetString("FileExtensionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to File Name Is Required.
        /// </summary>
        public static string FileNameIsRequired {
            get {
                return ResourceManager.GetString("FileNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to File Size Is Required.
        /// </summary>
        public static string FileSizeIsRequired {
            get {
                return ResourceManager.GetString("FileSizeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Google User Name Is Required.
        /// </summary>
        public static string GoogleUserNameIsRequired {
            get {
                return ResourceManager.GetString("GoogleUserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Id Is Required.
        /// </summary>
        public static string IdIsRequired {
            get {
                return ResourceManager.GetString("IdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Image Bytes Is Required.
        /// </summary>
        public static string ImageBytesIdIsRequired {
            get {
                return ResourceManager.GetString("ImageBytesIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Image Bytes Is Required.
        /// </summary>
        public static string ImageBytesIsRequired {
            get {
                return ResourceManager.GetString("ImageBytesIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Image Id Is Required.
        /// </summary>
        public static string ImageIdIsRequired {
            get {
                return ResourceManager.GetString("ImageIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Image Is Required.
        /// </summary>
        public static string ImageIsRequired {
            get {
                return ResourceManager.GetString("ImageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Id.
        /// </summary>
        public static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to LCID Decimal Is Required.
        /// </summary>
        public static string LCIDDecimalIsRequired {
            get {
                return ResourceManager.GetString("LCIDDecimalIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to LinkedIn User Name Is Required.
        /// </summary>
        public static string LinkedInUserNameIsRequired {
            get {
                return ResourceManager.GetString("LinkedInUserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to MimeType Is Required.
        /// </summary>
        public static string MimeTypeIdIsRequired {
            get {
                return ResourceManager.GetString("MimeTypeIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to MimeType Is Required.
        /// </summary>
        public static string MimeTypeIsRequired {
            get {
                return ResourceManager.GetString("MimeTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name Is Required.
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Notes Are Required.
        /// </summary>
        public static string NotesIsRequired {
            get {
                return ResourceManager.GetString("NotesIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} cannot be null or empty string.
        /// </summary>
        public static string NullOrEmpty {
            get {
                return ResourceManager.GetString("NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Parameter.
        /// </summary>
        public static string ParameterInvalid {
            get {
                return ResourceManager.GetString("ParameterInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Null Parameter.
        /// </summary>
        public static string ParameterNull {
            get {
                return ResourceManager.GetString("ParameterNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Phone Number Is Required.
        /// </summary>
        public static string PhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("PhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Phone Number Type is Required.
        /// </summary>
        public static string PhoneNumberTypeIsRequired {
            get {
                return ResourceManager.GetString("PhoneNumberTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Picture Is Required.
        /// </summary>
        public static string PictureIdIsRequired {
            get {
                return ResourceManager.GetString("PictureIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Picture Is Required .
        /// </summary>
        public static string PictureIsRequired {
            get {
                return ResourceManager.GetString("PictureIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Plugin Is Required.
        /// </summary>
        public static string PluginIsRequired {
            get {
                return ResourceManager.GetString("PluginIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Postal Code.
        /// </summary>
        public static string PostalCodeInvalid {
            get {
                return ResourceManager.GetString("PostalCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be between {1} and {2} characters.
        /// </summary>
        public static string RangeAttribute_ValidationError {
            get {
                return ResourceManager.GetString("RangeAttribute_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Rate Is Required.
        /// </summary>
        public static string RateIsRequired {
            get {
                return ResourceManager.GetString("RateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Record Not Found.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to State Is Required.
        /// </summary>
        public static string StateOrProvinceIsRequired {
            get {
                return ResourceManager.GetString("StateOrProvinceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Must be less than {1} characters.
        /// </summary>
        public static string StringLengthAttribute_InvalidMax {
            get {
                return ResourceManager.GetString("StringLengthAttribute_InvalidMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} must be between &apos;{2}&apos; and &apos;{1}&apos; characters.
        /// </summary>
        public static string StringLengthAttribute_InvalidMaxMin {
            get {
                return ResourceManager.GetString("StringLengthAttribute_InvalidMaxMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Subject Is Required.
        /// </summary>
        public static string SubjectIsRequired {
            get {
                return ResourceManager.GetString("SubjectIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to System Name Is Required.
        /// </summary>
        public static string SystemNameIsRequired {
            get {
                return ResourceManager.GetString("SystemNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to TimeZone Is Required.
        /// </summary>
        public static string TimeZoneIdIsRequired {
            get {
                return ResourceManager.GetString("TimeZoneIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to TimeZone Id Is Required.
        /// </summary>
        public static string TimeZoneInfoIdIsRequired {
            get {
                return ResourceManager.GetString("TimeZoneInfoIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Title Is Required.
        /// </summary>
        public static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Twitter Screen Name Is Required.
        /// </summary>
        public static string TwitterScreenNameIsRequired {
            get {
                return ResourceManager.GetString("TwitterScreenNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type Is Required.
        /// </summary>
        public static string TypeIsRequired {
            get {
                return ResourceManager.GetString("TypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to UserName Is Invalid.
        /// </summary>
        public static string UserNameIsInvalid {
            get {
                return ResourceManager.GetString("UserNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to UserName Is Required.
        /// </summary>
        public static string UserNameIsRequired {
            get {
                return ResourceManager.GetString("UserNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User Profile Bytes Is Required.
        /// </summary>
        public static string UserProfileBytesIdIsRequired {
            get {
                return ResourceManager.GetString("UserProfileBytesIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User Profile Id Is Invalid.
        /// </summary>
        public static string UserProfileIdIsInvalid {
            get {
                return ResourceManager.GetString("UserProfileIdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User Profile Picture Bytes Is Required.
        /// </summary>
        public static string UserProfilePictureBytesIdIsRequired {
            get {
                return ResourceManager.GetString("UserProfilePictureBytesIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User Profile Picture Is Required.
        /// </summary>
        public static string UserProfilePictureIdIsRequired {
            get {
                return ResourceManager.GetString("UserProfilePictureIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value Is Required.
        /// </summary>
        public static string ValueIsRequired {
            get {
                return ResourceManager.GetString("ValueIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value Type Is Required.
        /// </summary>
        public static string ValueTypeIsRequired {
            get {
                return ResourceManager.GetString("ValueTypeIsRequired", resourceCulture);
            }
        }
    }
}
